### ISSUE TITLE
when multiple value files, possibly bad?

### ISSUE THREAD

**Issue by jesstracy** [callrail/helm-ssm#15]
When you pass in more than one values file that share upper-level keys, helm-ssm does not consolidate them.

Example:
#### file-1.yaml
```
global:
  domain: eks.callrail.com

app:
  config: blah
```
#### file-2.yaml
```
global:
  notifySlack: true
```

#### resulting values file behind the scenes
```
global:
  domain: eks.callrail.com

app:
  config: blah

global:
  notifySlack: true
```
Instead of just one `global` section with both children underneath.

I have no idea if helm is smart enough to consolidate those for us since we don't consolidate here. needs testing and fix if not
